### ISSUE TITLE
is the same code to preprocess cityscapes?

### ISSUE THREAD

**Issue by pkuCactus** [Chrisding/sbd-preprocess#1]
thanks for sharing the code to preprocess the data, but  are both the code to preprocess cityscapes same, thanks a lot

**Comment by Chrisding** [comment]
Hi, the edge generation on Cityscapes is exactly the same as this one, except no data augmentation is performed. The parameters in the code are already the default values used in CASENet.

**Comment by pkuCactus** [comment]
ok, thanks a lot for your reply

**Comment by Chrisding** [comment]
I've updated the edge generation code for cityscapes, in case you need it:
https://github.com/Chrisding/cityscapes-preprocess
